version: 1.0
info: >
    The multiparameter, per-segment 
    power consumption forecast
    algorithm

logging:
    level: DEBUG
    # filename: quick_ann.log    

scenario:
    - data_loader:
        data_source:
            data_path: [".", DATA]
            archive_file_name: 6000_frame.zip
            file_name: 6000_frames_20221124+25_new.pkl
            delimiter: ","
        target:
            store_key: raw_data

    - data_preparation:
        data_source:
            store_key: raw_data
        processing:
            valid_data_range: [40001, 67000]
            processing_columns:
                - Timestamp
                - Battery cell voltage
                - ActualSpeed_L
                - ActualSpeed_R
                - Current segment
                - Speed
                - Cumulative energy consumption
                - Momentary current consuption
                - Momentary energy consumption
                - Momentary power consumption
            aggregated_columns:
                Mass:
                    - Weight statuses - front left strain gauge weight
                    - Weight statuses - front right strain gauge weight
                    - Weight statuses - rear left strain gauge weight
                    - Weight statuses - rear right strain gauge weight
            rename_columns:
                Current segment: Current segment
            index: Timestamp
        target:
            store_key: preformatted_data

    - data_segmentation:
        data_source:
            store_key: preformatted_data
        processing:
            segmentation_column: Current segment
            ignore_segments: [0, -10]
        target:
            store_key: segments_historical_data

    - build_per_segment_statistics:
        data_source:
            store_key: segments_historical_data
        processing:
            datetime_format: "%Y-%m-%d %H:%M:%S.%f"
        target:
            store_key: segments_historical_data

    - segments_route_re_format:
        processing:
            valid_data_range: [200, 600]
            processing_columns:
                - Segment 
                - Samples count 
                - Duration
                - Voltage delta
                - Start segment voltage

    - construct_ann:
        processing:
            input_parameters:
                - Segment 
                - Samples count 
                - Duration
                - Voltage delta
                - Start segment voltage
            static_parameters: ['Segment','Samples count','Duration','Voltage delta']
            forecast_parameters: ['Start segment voltage']
            input_neurons_per_parameter: 12
            hidden_layer_neurons_per_parameter: 17
            learn_samples_count: 350
            forecasted_samples_count: 38
            epochs_count: 50
            batch_size: 15

    - ann_prediction:
        # predict_steps_count: 10
    